[package]
name    = "bismark-genome-prep"
version = "0.25.1"
edition = "2021"

[[bin]]
name = "bismark_genome_preparation"
path = "src/main.rs"

[dependencies]
bismark-lib = { workspace = true }
clap        = { workspace = true }
anyhow      = { workspace = true }
flate2      = { workspace = true }
walkdir     = { workspace = true }
