[package]
name    = "bismark-coverage2cytosine"
version = "0.25.1"
edition = "2021"

[[bin]]
name = "coverage2cytosine"
path = "src/main.rs"

[dependencies]
bismark-lib  = { workspace = true }
clap         = { workspace = true }
anyhow       = { workspace = true }
flate2       = { workspace = true }
indexmap     = { workspace = true }

[dev-dependencies]
tempfile = "3"
